name: lint
on:
  push:
    branches-ignore:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: bufbuild/buf-lint-action@v1
      #- uses: bufbuild/buf-breaking-action@v1
      #  with:
      #    against: https://github.com/${{ github.repository }}.git#branch=main
